export const Preguntas = [
  {
    id: 1,
    pregunta: "¿En qué lugar se ejecuta generalmente el código JavaScript?",
    respuesta1: "Navegador del servidor",
    respuesta2: "Navegador del Cliente",
    respuesta3: "En papel",
    fotografia: "../assets/javascript.png",
    solucion: "Navegador del Cliente",
    estilo: "javascript",
  },

  {
    id: 2,
    pregunta:
      "¿Cuáles de estas son marcas para la inserción del código JavaScript en las páginas HTML?",
    respuesta1: "< javascript _code > y < /javascript_code >",
    respuesta2: "< script href=''/>",
    respuesta3: "Ninguna de las anteriores",
    fotografia: "../assets/javascript.png",
    solucion: "Ninguna de las anteriores",
    estilos: "javascript",
  },

  {
    id: 3,
    pregunta: "La llamada al código Javascript debe colocarse en:",
    respuesta1: "En el BODY",
    respuesta2: "Antes de la etiqueta HTML",
    respuesta3: "Puede colocarse en la sección Head o en Body",
    fotografia: "../assets/javascript.png",
    solucion: "Puede colocarse en la sección Head o en Body",
    estilos: "javascript",
  },
  {
    id: 4,
    pregunta:
      "En JavaScript, para darle el nombre a una variable, objeto o función, debemos tener en cuenta que:",
    respuesta1: "No se pueden usar mayúsculas",
    respuesta2: "JavaScript no distingue entre mayúsculas y minúsculas",
    respuesta3: "JavaScript diferencia entre mayúsculas y minúsculas",
    fotografia: "../assets/javascript.png",
    solucion: "JavaScript diferencia entre mayúsculas y minúsculas",
    estilos: "javascript",
  },
  {
    id: 5,
    pregunta: "¿Para qué sirve la función isNaN?",
    respuesta1:
      "Devuelve verdadero si el argumento no es un número porque de lo contrario arrojaría un falso.",
    respuesta2:
      "Devuelve falso si el argumento no es un número porque de lo contrario arrojaría un verdadero.",
    respuesta3:
      "Devuelve verdadero si el argumento es un número porque de lo contrario arrojaría un falso.",
    fotografia: "../assets/javascript.png",
    solucion:
      "Devuelve verdadero si el argumento no es un número porque de lo contrario arrojaría un falso.",
    estilos: "javascript",
  },
  {
    id: 6,
    pregunta: "¿Qué empresa desarrolló JavaScript?",
    respuesta1: "Microsoft",
    respuesta2: "Netscape",
    respuesta3: "Oracle",
    fotografia: "../assets/javascript.png",
    solucion: "Netscape",
    estilos: "javascript",
  },
  {
    id: 7,
    pregunta: "¿Qué es el operador ===?",
    respuesta1: "Igualdad simple",
    respuesta2: "Igualdad obligatoria",
    respuesta3: "Igualdad estricta",
    fotografia: "../assets/javascript.png",
    solucion: "Igualdad estricta",
    estilos: "javascript",
  },
  {
    id: 8,
    pregunta: "¿Cuál sería el resultado de 3+2+''7'' en Javascript?",
    respuesta1: "12",
    respuesta2: "57",
    respuesta3: "Da un error",
    fotografia: "../assets/javascript.png",
    solucion: "57",
    estilos: "javascript",
  },
  {
    id: 9,
    pregunta: "¿Qué significa NULL en Javascript?",
    respuesta1: "Representa un valor vació.",
    respuesta2: "Representa un valor nulo.",
    respuesta3: "Todas las anteriores",
    fotografia: "../assets/javascript.png",
    solucion: "Representa un valor nulo.",
    estilos: "javascript",
  },
  {
    id: 10,
    pregunta: "¿Explique el método pop() en JavaScript?",
    respuesta1: "Aparta el primer elemento del array dado.",
    respuesta2: "Aparta el último elemento del array dado.",
    respuesta3: "Es un método general de Javascript",
    fotografia: "../assets/javascript.png",
    solucion: "Aparta el último elemento del array dado.",
    estilos: "javascript",
  },
  {
    id: 11,
    pregunta:
      "¿Qué palabra clave se utiliza para mostrar un texto en pantalla?",
    respuesta1: "document.innerHTML()",
    respuesta2: "document.write()",
    respuesta3: "document.getElementById()",
    fotografia: "../assets/javascript.png",
    solucion: "document.write()",
    estilo: "javascript",
  },

  {
    id: 12,
    pregunta: "¿Cuál es la forma de obtener el estado de un CheckBox?",
    respuesta1: "document.getElementById('checkbox1').check",
    respuesta2: "document.getElementById('checkbox1').checked",
    respuesta3: "document.getElementById('checkbox1').value",
    fotografia: "../assets/javascript.png",
    solucion: "document.getElementById('checkbox1').checked",
    estilos: "javascript",
  },

  {
    id: 13,
    pregunta:
      "¿Cuál es la instrucción usada para devolver un valor en una función de JavaScript?",
    respuesta1: "getValue",
    respuesta2: "return",
    respuesta3: "get",
    fotografia: "../assets/javascript.png",
    solucion: "return",
    estilos: "javascript",
  },
  {
    id: 14,
    pregunta:
      "¿Cuál de estas instrucciones está correctamente escrita en Javascript?",
    respuesta1: "if (a==0) alert (a);",
    respuesta2: "if (a=0) print a;",
    respuesta3: "if (a==0) { print [a] }",
    fotografia: "../assets/javascript.png",
    solucion: "if (a==0) alert (a);",
    estilos: "javascript",
  },
  {
    id: 15,
    pregunta:
      "¿Cuál de las siguientes es una forma correcta de recorrer una colección de datos de tipo Array?",
    respuesta1: "[4, 5, 6].each(function(i){ return i})",
    respuesta2: "[4, 5, 6].forEach(function(i){ return i})",
    respuesta3: "[4, 5, 6].for(function(i){ return i})",
    fotografia: "../assets/javascript.png",
    solucion: "[4, 5, 6].forEach(function(i){ return i})",
    estilos: "javascript",
  },
];
